import { StyleSheet } from 'react-native';

export const colors = {
  primary: '#5BC5A7',
  primaryBg: '#f0fdf4',
  text: '#111827',
  muted: '#6b7280',
  mutedSoft: '#9ca3af',
  border: '#e5e7eb',
  bg: '#fff',
  surface: '#f3f4f6',
  danger: '#ef4444',
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    backgroundColor: colors.bg,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  cancelButton: { paddingVertical: 8, paddingHorizontal: 4 },
  cancelText: { fontSize: 16, color: colors.primary, fontWeight: '500' },
  headerTitle: { fontSize: 17, fontWeight: '600', color: colors.text },
  headerSpacer: { width: 60 },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 8,
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 44,
  },
  searchIcon: { marginRight: 8 },
  searchInput: { flex: 1, fontSize: 16, color: colors.text, paddingVertical: 0 },
  addNewButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 8,
  },
  addIcon: { marginRight: 10 },
  addNewText: { fontSize: 16, color: colors.primary, fontWeight: '500' },
  listContainer: { flex: 1, paddingTop: 8 },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  listContent: { paddingBottom: 100 },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.bg,
  },
  avatarContainer: { marginRight: 12 },
  avatarCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { fontSize: 18, fontWeight: '600', color: '#4b5563' },
  contactInfo: { flex: 1 },
  contactName: { fontSize: 16, fontWeight: '500', color: colors.text, marginBottom: 2 },
  contactPhone: { fontSize: 14, color: colors.muted },
  radioContainer: { marginLeft: 12 },
  radioOuter: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: '#d1d5db',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOuterSelected: { borderColor: colors.primary },
  radioInner: { width: 12, height: 12, borderRadius: 6, backgroundColor: colors.primary },
  separator: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.border,
    marginLeft: 72,
  },
  selectedSection: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  selectedSectionTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 12,
  },
  selectedScrollContent: { paddingRight: 16 },
  selectedAvatarContainer: { marginRight: 12, position: 'relative' },
  selectedAvatarCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedAvatarText: { fontSize: 20, fontWeight: '600', color: colors.bg },
  removeButton: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: colors.danger,
    borderRadius: 10,
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nextButtonContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingBottom: 24,
    backgroundColor: colors.bg,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  nextButton: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nextButtonDisabled: { backgroundColor: colors.border },
  nextButtonText: { fontSize: 16, fontWeight: '600', color: colors.bg },
  nextButtonTextDisabled: { color: colors.mutedSoft },
  manualSheetContainer: { flex: 1, backgroundColor: colors.bg },
  manualHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    backgroundColor: colors.bg,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  manualCloseButton: { padding: 4 },
  manualHeaderTitle: { fontSize: 17, fontWeight: '600', color: colors.text },
  manualHeaderSpacer: { width: 32 },
  manualContent: { flex: 1 },
  manualContentInner: { padding: 16 },
  manualInputGroup: { marginBottom: 24 },
  manualLabel: { fontSize: 14, fontWeight: '500', color: colors.muted, marginBottom: 8 },
  manualInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    color: colors.text,
    backgroundColor: colors.bg,
  },
  manualButtonContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingBottom: 24,
    backgroundColor: colors.bg,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  manualDoneButton: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  manualDoneButtonDisabled: { backgroundColor: colors.border },
  manualDoneButtonText: { fontSize: 16, fontWeight: '600', color: colors.bg },
  manualDoneButtonTextDisabled: { color: colors.mutedSoft },
  loadingContainer: { paddingVertical: 40, alignItems: 'center', justifyContent: 'center' },
  loadingText: { marginTop: 12, fontSize: 14, color: colors.muted },
  emptyContactsContainer: { paddingVertical: 40, alignItems: 'center', justifyContent: 'center' },
  emptyContactsText: { fontSize: 14, color: colors.muted },
  permissionDeniedContainer: {
    paddingVertical: 60,
    paddingHorizontal: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  permissionDeniedTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.text,
    marginTop: 16,
    marginBottom: 8,
    textAlign: 'center',
  },
  permissionDeniedText: {
    fontSize: 14,
    color: colors.muted,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 24,
  },
  permissionButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  permissionButtonText: { color: colors.bg, fontSize: 16, fontWeight: '600' },
});
